{% set version = "0.1.4" %}

package:
  name: scarplet
  version: {{ version }}

source:
  url: https://github.com/rmsare/scarplet/archive/v{{ version }}.tar.gz
  sha256: 29f0ed2dc8bee013bea9269f05ea7eb440d17d93f549b0373536a2f4a98249cf

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numexpr
    - numpy
    - matplotlib
    - gdal
    - pyfftw
    - rasterio
    - scipy

test:
  imports:
    - scarplet

about:
  home: http://github.com/rmsare/scarplet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Topographic edge detection of fault scarps and other landforms in digital elevation data
  description: |
    A Python package for applying template matching techniques to
    digital elevation data, in particular for detecting and measuring
    the maturity of fault scarps and other landforms.
  doc_url: https://scarplet.readthedocs.io
  dev_url: http://github.com/rmsare/scarplet

extra:
  recipe-maintainers:
    - mcflugen
    - rmsare
