travis:
  secure:
    BINSTAR_TOKEN: SD8d8K3S43BupENLO3ewxXsoJzJ/1ma8VJ9MP5bXsbKPsgwudzm5Enhe3ba/US7dWvYMjL45K0Hrg8jZqNQXrDPbBoH7OUjWFncB2y3/rCjwd+A3yXzUyzyr1BJxgA64PaCG3FdNoZ0X2IDVaHhpVT1kbxkR+g2paBBYXHROPsMPYuq7lMO1NMZkIqT2Uooh6PfOfH1N3rqWa4UglyFGKOZxpZh36pTa6douE82qKXguIYp1y7M1zz/81GrK+YqbhClO+jv8IIXime+PSymfZsbuDEIQGOucAfBS4M+maqJOWCUCoZsGcp3lWBXhTBP6bP7YOzTgwsa6nc2wPjeElUSRZQpKYCOf0sRwrVRr3lurjn+TJoJHEdk2TodSNIy9Ld5ioWaePKZnfkj0dXB0j8xRQ/QUGtBojMQSW4IAUsOLIDTdO1F+CoVQzzoeyBxWHG+u/wD7H2pb6em3bpP6m6V1oO3pqcm2CrqxCuG/79sJdO+wor4X57izLfAEGrKkog9IZ6CJLCVMmfZyqH7/kpCkHpwHQ/kIiZ0yQdVbF6l647W0RRRKPA7jnNWuWtvovL5WtvpH2yQTq8GG1Kk3wF3w52Mc3Wj4nCmMwI306fUyiJR6JFGa3M4iJMvPw8FPzGqbXVlVIFwQfCaoGuNZ7MiP3sE+zQDtD0+rT79DmxM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
